application:
  clusterId : "Cluster1"
task:
  utilisationReportingInterval: 1s
  missingJobEventReconciliationInterval: 15s
  stuckPodScanInterval: 15s
  jobLeaseRenewalInterval: 15s
  podDeletionInterval: 5s
  allocateSpareClusterCapacityInterval: 5s
armada:
  url : "localhost:50051"
basicAuth:
  enableAuthentication: false
metricsPort: 9001